<?php

/**
 * adMassageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adMassageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adMassageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adMassage');
    }

    public static function getAllMassage()
    {
        return adMassageTable::getInstance()->createQuery()
            ->fetchArray();
    }

    public static function checkSlug($slug)
    {
        return adMassageTable::getInstance()->createQuery()
            ->where('slug=?', $slug)
            ->fetchArray();
    }

    public static function getListMassage($limit = 8, $offset = 0)
    {
        $query = adMassageTable::getInstance()->createQuery()
            ->andWhere('is_active=?', 1)
            ->orderBy('priority desc, updated_at desc')
            ->limit($limit)
            ->offset($offset)
            ->fetchArray();
        if (!empty($query)) {
            return $query;
        }
        return false;
    }
}