<?php

/**
 * adMassageImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adMassageImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adMassageImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adMassageImage');
    }
}