<?php

/**
 * adMassageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adMassageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adMassageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adMassage');
    }

    public static function getAllMassage()
    {
        return adMassageTable::getInstance()->createQuery()
            ->fetchArray();
    }
}